### ISSUE TITLE
rebase 기능도 있던데 참고해보세요~

### ISSUE THREAD

**Issue by jonggyun** [yhmane/git#1]
https://git-scm.com/book/ko/v1/Git-%EB%B8%8C%EB%9E%9C%EC%B9%98-Rebase%ED%95%98%EA%B8%B0

예전에 면접보러 갔을 때, 물었던 적 있습니다. 
Q: 자잘하게 커밋을 많이 하시던데, 커밋합치는 방법에 대해서는 모르시는지요?
A: 네, 모릅니다..........

추가로 
http://woowabros.github.io/experience/2017/10/30/baemin-mobile-git-branch-strategy.html
이런 방법론?도 있으니 참고하시옵소서

**Comment by yhmane** [comment]
저런 기능이 있는 줄은 ....
커밋이 좀 지저분한데 찾아 봐야겠네여 ㅎㅎ

감사합니다:)

**Comment by yhmane** [comment]
> https://git-scm.com/book/ko/v1/Git-%EB%B8%8C%EB%9E%9C%EC%B9%98-Rebase%ED%95%98%EA%B8%B0
> 
> 예전에 면접보러 갔을 때, 물었던 적 있습니다.
> Q: 자잘하게 커밋을 많이 하시던데, 커밋합치는 방법에 대해서는 모르시는지요?
> A: 네, 모릅니다..........
> 
> 추가로
> http://woowabros.github.io/experience/2017/10/30/baemin-mobile-git-branch-strategy.html
> 이런 방법론?도 있으니 참고하시옵소서

rebase는 처음 듣는데, 찾아봐야 겠군요 ㅎㅎ
감사합니다 :)
